```{r}
# Imports data
library(ggplot2)
library(tidyr)
data <- read.csv("Texas_Precinct_Election_Data.csv")
head(data)
```
```{r}
adjusted_data <- pivot_longer(data, Trump_2020_Votes:O_Rourke_2022_Votes, names_to = "Campaign", values_to = "Votes")
head(adjusted_data)
```
```{r}
# Creates 2 different data frames for each election
pres_2020_data = subset(adjusted_data, Campaign %in% c('Trump_2020_Votes', 'Biden_2020_Votes'))
gov_2022_data = subset(adjusted_data, Campaign %in% c('Abbott_2022_Votes', 'O_Rourke_2022_Votes'))
head(pres_2020_data)
head(gov_2022_data)
```




```{r}
ggplot(data = pres_2020_data, aes(x = Latino_VAP_2022_Pct, y = Votes/Total_Votes_2020_Pres, color = Campaign)) + geom_point(size = 1, alpha = 0.1) + geom_smooth(method = 'lm') + scale_color_manual(values = c('blue', 'red'), labels = c('Biden', 'Trump')) + labs(title = "2020 Presidential Election Results by Precinct's Share of White Voters", x = "Share of White Voters", y = "Share of Votes") + theme(plot.title=element_text(hjust=0.5))

```

```{r}
ggplot(data = data, aes(x = (1 - White_VAP_2022_Pct), y = Change_in_Turnout)) + geom_point(size = 1, alpha = 0.1, color = 'purple') + geom_smooth(method = 'lm', color = 'purple') + labs(title = "Change in Voter Turnout from 2020 to 2022", x = "Percentage of Non-White Voters", y = "Change in Turnout (%)") + ylim(-75, 25) + theme(plot.title=element_text(hjust=0.5))
```

```{r}
hist(data$Asian_VAP_2022_Pct* 100, main = 'Percentage of White Voters in TX Precincts', col = 'purple')
```
```{r}
ggplot(data = data, aes(x = (White_VAP_2022_Pct) * 100, y = ((O_Rourke_2022_Pct - Abbott_2022_Pct) - (Biden_2020_Pct - Trump_2020_Pct)) * 100)) + geom_point(size = 1, alpha = 0.1, color = 'purple') + geom_smooth(method = 'lm', color = 'purple') + labs(title = "Beto vs Biden Margin", x = "Percentage of Non-White Voters", y = "Beto vs Biden Margin (%)") + ylim(-50, 50)
```
```{r}
subdata <- subset(data, Asian_VAP_2022_Pct > 50)
subdata
biden_pct = sum(subdata$Biden_2020_Votes) / sum(subdata$Total_Votes_2020_Pres) * 100
trump_pct = sum(subdata$Trump_2020_Votes) / sum(subdata$Total_Votes_2020_Pres) * 100
o_rourke_pct = sum(subdata$O_Rourke_2022_Votes) / sum(subdata$Total_Votes_2022_Gov) * 100
abbott_pct = sum(subdata$Abbott_2022_Votes) / sum(subdata$Total_Votes_2022_Gov) * 100
biden_pct
trump_pct
o_rourke_pct
abbott_pct
(o_rourke_pct - abbott_pct - biden_pct + trump_pct)
```
```{r}
subset(data, (Asian_VAP_2022_Pct * 100) > 50)
```
```{r}
sdata <- subset(data, Dem_Raw_Vote_Margin_Gain < 0)
ddd <- sum(abs(sdata$Dem_Raw_Vote_Margin_Gain))
ddd
```

